/* Generated By:JavaCC: Do not edit this line. Assignment.java */
  import java.util.*;
  public class Assignment implements AssignmentConstants {
    public static ArrayList<String> functionCalls = new ArrayList<String>();
    public static ArrayList<String> functionNames = new ArrayList<String>();

    //Maps function names to their parameters
    public static HashMap<String, Character> functionParams = new HashMap<String, Character>();

    public static void main(String args []) throws Exception {
      try {
        new Assignment(System.in).Start();
        System.out.println("Syntax is okay: PASS");
      } catch (Exception e) {
        System.out.println("Syntax error detected: FAIL");
        System.err.println(e.getMessage());
      }
    }

// TOKEN: { < DEFINE: <DEF> <SPACE> > }

//Lexical Specification

//(1) - [CORRECT]   //(2) - [CORRECT]   //(3) - [CORRECT]
//(4) - [CORRECT]   //(5) - [CORRECT]   //(6) - [CORRECT]
//(7) - [INCORRECT] //(8) - [INCORRECT]   //(9) - [CORRECT]
//(10) - [CORRECT]  //(11) - [CORRECT]  //(12) - [CORRECT]

//TODO: (7) - Make sure associated parameters are used in function bodies # hashmap
//TODO: (8) - Make sure function calls refer to defined functions in the same file #
  final public void Definition() throws ParseException {
    try {
      jj_consume_token(DEF);
      jj_consume_token(SPACE);
    } catch (ParseException e) {
                               //Catch error thrown for wrong beginning of line
    //get line number and then throw error
    // int lineNumber = e.getStackTrace()[0].getLineNumber();
    System.out.println("Error: ");
    }
  }

  final public void Start() throws ParseException {
    Program();
    jj_consume_token(0);
  }

//Program -> (Function() | Main())*
  final public void Program() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DEF:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Definition();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FUNC:
        Function();
        break;
      case MAIN:
        Main();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//Main -> MAIN FunctionBody
  final public void Main() throws ParseException {
    jj_consume_token(MAIN);
    FunctionBody();
  }

//Function -> FUNC PARAM FunctionBody
  final public void Function() throws ParseException {
    jj_consume_token(FUNC);
    jj_consume_token(SPACE);
    jj_consume_token(PARAM);
    FunctionBody();
  }

//FunctionBody -> LBRACE EXPR RBRACE SCOLON EOL
  final public void FunctionBody() throws ParseException {
    jj_consume_token(SPACE);
    jj_consume_token(LBRACE);
    jj_consume_token(SPACE);
    Expression();
    jj_consume_token(SPACE);
    jj_consume_token(RBRACE);
    jj_consume_token(SPACE);
    jj_consume_token(SCOLON);
    jj_consume_token(EOL);
  }

//EXPR -> TERM ADD TERM | TERM
  final public void Expression() throws ParseException {
    Term();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      jj_consume_token(ADD);
      Term();
    }
  }

//TERM -> FACTOR MUL FACTOR | FACTOR
  final public void Term() throws ParseException {
    Factor();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MUL:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      jj_consume_token(MUL);
      Factor();
    }
  }

//FACTOR -> NUM | Function | Parameter
  final public void Factor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FUNC:
      Function_Call();
      break;
    case PARAM:
      jj_consume_token(PARAM);
      break;
    case NUM:
      jj_consume_token(NUM);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//Function_Call -> FUNC LPAREN EXPR RPAREN
  final public void Function_Call() throws ParseException {
    jj_consume_token(FUNC);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
  }

  /** Generated Token Manager. */
  public AssignmentTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x400,0x1800,0x8,0x10,0x7000,};
   }

  /** Constructor with InputStream. */
  public Assignment(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Assignment(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new AssignmentTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Assignment(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AssignmentTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Assignment(AssignmentTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AssignmentTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[15];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 15; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  }
